stages:
  - build
  - build-docker

build:
  stage: build
  image: registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/maven:3.6.3-jdk-8
  variables:
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress
      -DinstallAtEnd=true
      -DdeployAtEnd=true
    SETTINGS_XML_PATH: settings.xml
  script:
    - echo $SETTINGS_XML_PATH
    - GROUP_ID=`mvn -e help:evaluate -Dexpression=project.groupId -q -DforceStdout -s $SETTINGS_XML_PATH`
    - ARTIFACT_ID=`mvn -e help:evaluate -Dexpression=project.artifactId -q -DforceStdout -s $SETTINGS_XML_PATH`
    - VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout -s $SETTINGS_XML_PATH`
    - echo $GROUP_ID
    - echo $ARTIFACT_ID
    - echo $VERSION
    - echo "GROUP_ID=$GROUP_ID" > .job_env
    - echo "ARTIFACT_ID=$ARTIFACT_ID" >> .job_env
    - echo "VERSION=$VERSION" >> .job_env
    - cat .job_env
    - mvn clean package source:jar javadoc:jar deploy -s $SETTINGS_XML_PATH
  artifacts:
    reports:
      dotenv: .job_env
    paths:
      - target/*.jar
  cache:
    paths:
      - .m2/repository

docker-build:
  image:
    # name: gcr.io/kaniko-project/executor:v1.23.0-debug
    name: registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/kaniko-project-executor:v1.23.0-debug
    entrypoint: [ "" ]
  stage: build-docker
  needs:
    - job: build
      artifacts: true
  before_script:
    - echo "{\"auths\":{\"registry.cn-qingdao.aliyuncs.com\":{\"auth\":\"$(printf "%s:%s" "${ACR_REGISTRY_USER}" "${ACR_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" ${DOCKER_USERNAME} "${DOCKER_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - echo $GROUP_ID
    - echo $ARTIFACT_ID
    - echo $VERSION
    - /kaniko/executor version
    - /kaniko/executor --help
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg "GROUP_ID=$GROUP_ID"
      --build-arg "ARTIFACT_ID=$ARTIFACT_ID"
      --build-arg "VERSION=$VERSION"
      --build-arg "CI_PIPELINE_URL=$CI_PIPELINE_URL"
      --build-arg "CI_JOB_ID=$CI_JOB_ID"
      --destination "registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/commons-lang3:$VERSION"
      --destination "registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/commons-lang3:$VERSION-$CI_PIPELINE_ID"
      --destination "xuxiaoweicomcn/commons-lang3:$VERSION"
      --destination "xuxiaoweicomcn/commons-lang3:$VERSION-$CI_PIPELINE_ID"
