stages:
  - build

build:
  stage: build
  #image: maven:3.6.3-openjdk-17
  image: registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/mvnd:1.0.1-dragonwell-17-anolis
  variables:
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress
      -DinstallAtEnd=true
      -DdeployAtEnd=true
    SETTINGS_XML_PATH: settings.xml
  script:
    - echo $SETTINGS_XML_PATH
    - free -h || cat /proc/meminfo
    - mvnd -v
    - mvnd clean package -DskipTests=true -s $SETTINGS_XML_PATH $MAVEN_OPTS
    - free -h || cat /proc/meminfo
    - nohup java -Xms128m -Xmx256m -jar demo/target/commons-lang3-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
  artifacts:
    name: build
    paths:
      - target/*.jar
  cache:
    paths:
      - .m2/repository
